language: generic

script:
  - echo "Deploying on gh-pages"

deploy:
  provider: pages
  local_dir: .
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
